import React, { useState, useEffect } from 'react';
import Header from './components/Header';
import SearchBar from './components/SearchBar';
import FreeTextSearch from './components/FreeTextSearch';
import QuizModal from './components/QuizModal';
import BookCard from './components/BookCard';
import BookDetailModal from './components/BookDetailModal';
import FavoritesDrawer from './components/FavoritesDrawer';
import ResultsGrid from './components/ResultsGrid';

import {
  fetchHealth,
  fetchGenres,
  searchBooks,
  recommendByBook,
  recommendByQuiz,
  recommendByText,
} from './services/api';

import { BookOpen, Sparkles, HelpCircle, Layers, Award, Heart } from 'lucide-react';

export default function App() {
  const [activeTab, setActiveTab] = useState('search');
  const [healthStatus, setHealthStatus] = useState(null);
  const [genres, setGenres] = useState([]);
  
  // Grid Results state
  const [books, setBooks] = useState([]);
  const [loading, setLoading] = useState(false);
  const [gridTitle, setGridTitle] = useState('Library Book Catalog');
  const [gridSubtitle, setGridSubtitle] = useState('Browse available titles in the Goodbooks-10k collection.');
  const [modeLabel, setModeLabel] = useState('Catalog Search');

  // Modals state
  const [selectedBookId, setSelectedBookId] = useState(null);
  const [isQuizOpen, setIsQuizOpen] = useState(false);
  const [isFavDrawerOpen, setIsFavDrawerOpen] = useState(false);

  // Favorites state (persisted in localStorage)
  const [favorites, setFavorites] = useState(() => {
    try {
      const saved = localStorage.getItem('alexandria_favorites');
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  useEffect(() => {
    localStorage.setItem('alexandria_favorites', JSON.stringify(favorites));
  }, [favorites]);

  // Initial Startup API Calls
  useEffect(() => {
    fetchHealth()
      .then(setHealthStatus)
      .catch((err) => console.warn('Health check failed:', err));

    fetchGenres()
      .then((data) => setGenres(data.genres || []))
      .catch((err) => console.warn('Genres load failed:', err));

    // Initial catalog fetch
    handleSearch({});
  }, []);

  // Search Handler
  const handleSearch = async (params = {}) => {
    setLoading(true);
    try {
      const res = await searchBooks(params);
      setBooks(res.books || []);
      setGridTitle(params.query ? `Search Results for "${params.query}"` : 'Library Book Catalog');
      setGridSubtitle('Filtered by your query and metadata constraints.');
      setModeLabel('Metadata Filter');
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // Recommend Similar to Book Handler
  const handleRecommendSimilar = async (book) => {
    setLoading(true);
    try {
      const res = await recommendByBook(book.book_id, 10, 0.5);
      setBooks(res.recommendations || []);
      setGridTitle(`Books Similar to "${book.title}"`);
      setGridSubtitle(`Generated by Hybrid Engine (TF-IDF Content + Collaborative Filtering) & Gemini AI.`);
      setModeLabel('Hybrid Book Similarity');
      window.scrollTo({ top: 400, behavior: 'smooth' });
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // Recommend by Quiz Handler
  const handleQuizComplete = async (answers) => {
    setLoading(true);
    try {
      const res = await recommendByQuiz(answers, 10);
      setBooks(res.recommendations || []);
      setGridTitle('Personalized Quiz Recommendations');
      setGridSubtitle('Crafted based on your selected mood, genre, and reading themes.');
      setModeLabel('Hybrid Quiz Recommender');
      setActiveTab('search');
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // Recommend by AI Free-Text Prompt Handler
  const handleRecommendByText = async (prompt) => {
    setLoading(true);
    try {
      const res = await recommendByText(prompt, 10);
      setBooks(res.recommendations || []);
      setGridTitle(`AI Recommendations for "${prompt}"`);
      setGridSubtitle('Candidates shortlisted by TF-IDF content similarity & re-ranked with Gemini AI reasons.');
      setModeLabel('Gemini LLM Re-Ranker');
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // Recommend from Session Favorites Handler
  const handleRecommendFromFavorites = async () => {
    if (favorites.length === 0) return;
    setLoading(true);
    try {
      // Pick top favorite book as seed
      const seed = favorites[0];
      const res = await recommendByBook(seed.book_id, 10, 0.5);
      setBooks(res.recommendations || []);
      setGridTitle('Recommendations Based on Your Saved Favorites');
      setGridSubtitle(`Matched against your preference for "${seed.title}".`);
      setModeLabel('Session Favorites Match');
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // Toggle Favorite
  const handleToggleFavorite = (book) => {
    setFavorites((prev) => {
      const exists = prev.some((f) => f.book_id === book.book_id);
      if (exists) {
        return prev.filter((f) => f.book_id !== book.book_id);
      } else {
        return [...prev, book];
      }
    });
  };

  return (
    <div style={styles.appWrapper}>
      {/* Top Header */}
      <Header
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        favoritesCount={favorites.length}
        onOpenFavorites={() => setIsFavDrawerOpen(true)}
        healthStatus={healthStatus}
      />

      {/* Hero Welcome Banner */}
      <div style={styles.heroBanner}>
        <div style={styles.heroContainer}>
          <div style={styles.heroText}>
            <span style={styles.heroTag}>✨ FAI Course Mini Project • Team AI&DS</span>
            <h1 style={styles.heroTitle}>AI-Powered Library Book Recommendation System</h1>
            <p style={styles.heroDesc}>
              Discover books using Content-Based TF-IDF vectorization, Item-Based Collaborative Filtering, and Google Gemini LLM grounded explanations.
            </p>
          </div>

          <div style={styles.heroQuickActions}>
            <button className="btn-primary" onClick={() => setIsQuizOpen(true)}>
              <HelpCircle size={18} />
              <span>Take Book Preference Quiz</span>
            </button>
            <button className="btn-secondary" onClick={() => setActiveTab('ai')}>
              <Sparkles size={18} color="#c69214" />
              <span>AI Free-Text Prompt</span>
            </button>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <main style={styles.mainContainer}>
        {/* Tab 1: Catalog Search & Filters */}
        {activeTab === 'search' && (
          <SearchBar
            genres={genres}
            onSearch={handleSearch}
            onReset={() => handleSearch({})}
          />
        )}

        {/* Tab 2: AI Free-Text Prompt Bar */}
        {activeTab === 'ai' && (
          <FreeTextSearch
            onRecommendByText={handleRecommendByText}
            loading={loading}
          />
        )}

        {/* Results Grid */}
        <ResultsGrid
          title={gridTitle}
          subtitle={gridSubtitle}
          modeLabel={modeLabel}
          books={books}
          loading={loading}
          onSelectBook={(b) => setSelectedBookId(b.book_id)}
          onRecommendSimilar={handleRecommendSimilar}
          favorites={favorites}
          onToggleFavorite={handleToggleFavorite}
        />
      </main>

      {/* Book Details Modal */}
      <BookDetailModal
        bookId={selectedBookId}
        onClose={() => setSelectedBookId(null)}
        onSelectBook={(b) => setSelectedBookId(b.book_id)}
        onToggleFavorite={handleToggleFavorite}
        isFavorite={favorites.some((f) => f.book_id === selectedBookId)}
      />

      {/* Quiz Modal */}
      <QuizModal
        isOpen={isQuizOpen || activeTab === 'quiz'}
        onClose={() => {
          setIsQuizOpen(false);
          if (activeTab === 'quiz') setActiveTab('search');
        }}
        onComplete={handleQuizComplete}
        booksList={books}
      />

      {/* Favorites Drawer */}
      <FavoritesDrawer
        isOpen={isFavDrawerOpen}
        onClose={() => setIsFavDrawerOpen(false)}
        favorites={favorites}
        onRemove={handleToggleFavorite}
        onRecommendFromFavorites={handleRecommendFromFavorites}
        onSelectBook={(b) => setSelectedBookId(b.book_id)}
      />

      {/* Cozy Footer */}
      <footer style={styles.footer}>
        <p>Alexandria AI Library Recommendation Engine • Built for Foundations of AI (FAI) Course Demo</p>
        <p style={{ fontSize: '0.78rem', color: '#9e877c', marginTop: '4px' }}>
          Hybrid Algorithm: TF-IDF Cosine Similarity + Item Collaborative Filtering + Google Gemini LLM
        </p>
      </footer>
    </div>
  );
}

const styles = {
  appWrapper: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  heroBanner: {
    backgroundColor: '#2b1810',
    backgroundImage: 'linear-gradient(180deg, #382219 0%, #2b1810 100%)',
    borderBottom: '1px solid #4a2d21',
    color: '#fcf9f2',
    padding: '36px 24px',
  },
  heroContainer: {
    maxWidth: '1280px',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '24px',
  },
  heroText: {
    maxWidth: '720px',
  },
  heroTag: {
    backgroundColor: '#7a3e1d',
    color: '#f7eed7',
    border: '1px solid #c69214',
    padding: '3px 10px',
    borderRadius: '20px',
    fontSize: '0.78rem',
    fontWeight: '600',
    display: 'inline-block',
    marginBottom: '10px',
  },
  heroTitle: {
    color: '#fcf9f2',
    fontSize: '2rem',
    margin: '0 0 10px 0',
    fontFamily: "'Playfair Display', Georgia, serif",
    lineHeight: 1.25,
  },
  heroDesc: {
    color: '#d4beab',
    fontSize: '0.98rem',
    margin: 0,
    lineHeight: 1.5,
  },
  heroQuickActions: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  mainContainer: {
    maxWidth: '1280px',
    width: '100%',
    margin: '0 auto',
    padding: '32px 24px',
    flex: 1,
  },
  footer: {
    backgroundColor: '#271710',
    borderTop: '1px solid #4a2d21',
    color: '#d4beab',
    textAlign: 'center',
    padding: '24px',
    fontSize: '0.85rem',
    marginTop: 'auto',
  },
};
